# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# <learder-key>:source-file ~/.tmux.conf
# or
# tmux source ~/.tmux.conf

# force non-login shell
set -g default-command "${SHELL}"

# change leader key to ctrl-space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# tmux scroll vim binding
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection                                                                                                                                                            
bind-key -T copy-mode-vi V send -X select-line
set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# plugins (<leader-key>+I to isntall, <leader-key>+U to update)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'
